title: Mike Chambers - AI/ML Notes
description: Personal notes and observations on artificial intelligence and machine learning

author:
  name: Mike Chambers
  email: "mike@mikegchambers.com"

# Theme setting
remote_theme: jekyll/minima

google_analytics: G-GP9Z38FL6F 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - title: YouTube
      icon: youtube
      url: "https://www.youtube.com/@mikegchambers"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/mikegchambers"
    - title: BlueSky
      icon: bluesky
      url: "https://bsky.app/profile/mikegchambers.com"

  # Show excerpts on the home page
  show_excerpts: true
