title: Mike Chambers - AI/ML Notes
description: Personal notes and observations on artificial intelligence and machine learning
author: Mike Chambers

# Theme setting
theme: minima

google_analytics: G-GP9Z38FL6F 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/mikegchambers"
    - title: BlueSky
      icon: mastodon  # Using mastodon icon as placeholder since BlueSky doesn't have a dedicated icon yet
      url: "https://bsky.app/profile/mikegchambers.com"

# Show excerpts on the home page
show_excerpts: true
